name: work_with_api
description: "Работа с API."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  shared_preferences: ^2.5.4
  curved_navigation_bar: ^1.0.6
  tab_indicator_styler: ^2.0.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:


  uses-material-design: true

  assets:
     - assets/



